name: flutter_turbo_serialport
description: "Usb serial port communication for Android platform"
repository: https://github.com/serserm/flutter_turbo_serialport
homepage: https://github.com/serserm/flutter_turbo_serialport
issue_tracker: https://github.com/serserm/flutter_turbo_serialport/issues
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.serserm.turboserialport
        pluginClass: TurboSerialportPlugin
