name: flutter_turbo_serialport
description: "This is a plugin for communication with Arduinos and other USB serial hardware on Android, using the felHR85/UsbSerial"
repository: https://github.com/serserm/flutter_turbo_serialport
homepage: https://github.com/serserm/flutter_turbo_serialport
issue_tracker: https://github.com/serserm/flutter_turbo_serialport/issues
version: 1.2.0

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.serserm.turboserialport
        pluginClass: TurboSerialportPlugin

topics:
  - android
  - usb
  - serialport
